image: node

default:
  tags:
    - pangea-internal

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - lint
  - unit_tests
  - integration_tests
  - publish

before_script:
  - yarn config set cache-folder .yarn
  - yarn install
  - cd ./examples/demo_app && yarn install && cd ../..

lint:
  stage: lint
  script:
    - yarn lint

testing:
  stage: unit_tests
  script:
    - yarn test:unit

integration:
  stage: integration_tests
  script:
    - yarn test:integration

publish:
  stage: publish
  only:
    - tags
  script:
    - yarn build
    - cat ${NPMRC} > .npmrc && npm publish && rm -rf .npmrc
