# Website deploy pipeline
image: node

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - apt-get install -qq rsync
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: site-test.pangea.cloud
  variables:
    DEPLOY_PATH: 'testsite'
  script:
    - bash deploy.sh
  only:
    - dev

deploy_production:
  stage: deploy
  environment:
    name: production
    url: pangea.cloud
  variables:
    DEPLOY_PATH: 'website'
  script:
    - bash deploy.sh
  only:
    - main
