image: node

default:
  tags:
    - pangea-internal

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - lint
  - unit_tests
  - integration_tests
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_PIPELINE_SOURCE == "push" # don't run a pipeline on every push, only every MR
      when: never

before_script:
  - yarn config set cache-folder .yarn
  - yarn install
  - cd ./examples/demo_app && yarn install && cd ../..

lint:
  stage: lint
  script:
    - yarn lint

testing:
  stage: unit_tests
  script:
    - echo "Unit tests..."

integration:
  stage: integration_tests
  script:
    - echo "Integration tests..."

publish:
  stage: publish
  only:
    - tags
  script:
    - yarn install
    - cat ${NPMRC} > .npmrc && npm publish && rm -rf .npmrc
