image: node

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - lint
  - unit_tests
  - integration_tests
  - publish

before_script:
  - yarn config set cache-folder .yarn
  - yarn install

lint:
  stage: lint
  script:
    - yarn lint

testing:
  stage: unit_tests
  script:
    - echo "Unit tests..."

integration:
  stage: integration_tests
  script:
    - echo "Integration tests..."

publish:
  stage: publish
  only:
    - tags
  script:
    - yarn install
    - cat ${NPMRC} > .npmrc && npm publish && rm -rf .npmrc
